#
# Copyright (c) 2024 Robert Bosch Manufacturing Solutions GmbH
#
# See the AUTHORS file(s) distributed with this work for additional
# information regarding authorship.
#
# See the LICENSE file(s) distributed with this work for
# additional information regarding license terms.
#

name: Upload Single Model
on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Path of the model to be uploaded'
        required: true
        default: 'model_path'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github
            io.catenax.generic.digital_product_passport/3.0.0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Node dependencies
        working-directory: ./.github/actions/model-validation
        run: npm install
      - name: validate models
        uses: ./.github/actions/model-validation
        with:
          bamm_version: 2.5.1
          bulk: false
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: full-validation-report
          path: output
